//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deudore
    {
        public int ID { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<double> Capital { get; set; }
        public Nullable<double> Interes { get; set; }
        public Nullable<System.DateTime> FechaInicializacionPrestamo { get; set; }
    }
}
